/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Model;

/**
 *
 * @author User
 */
public class TelaIngressos extends javax.swing.JFrame {

    /**
     * Creates new form TelaIngressos
     */
    public TelaIngressos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ButtonMeia = new javax.swing.JButton();
        ButtonInteira = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ingressos.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, -1, -1));

        ButtonMeia.setText("jButton1");
        ButtonMeia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonMeiaActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonMeia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 310, 310));

        ButtonInteira.setText("jButton2");
        ButtonInteira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonInteiraActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonInteira, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 320, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonMeiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonMeiaActionPerformed
         TelaFormasDePagamento tfp = new TelaFormasDePagamento();
     tfp.setVisible(true);
    }//GEN-LAST:event_ButtonMeiaActionPerformed

    private void ButtonInteiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonInteiraActionPerformed
        TelaFormasDePagamento tfp = new TelaFormasDePagamento();
     tfp.setVisible(true);
    }//GEN-LAST:event_ButtonInteiraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaIngressos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaIngressos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaIngressos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaIngressos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaIngressos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonInteira;
    private javax.swing.JButton ButtonMeia;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
